config/routes.rb
Booksonrails::Application.routes.draw do

  resources :books do
    post 'add_to_my_books', :action => :add_to_my_books
    post 'add_to_my_books2', :action => :add_to_my_books2
  end
  resources :users do
    resources :assistances do
      post 'take_book', :action => :take_book
      post 'untake_book', :action => :untake_book
    end
    resources :exemplars do
      get 'search_by_title', :on => :collection
    end
  end
  resources :sessions
  root :to => redirect('/sessions/new')
  match '/home', :to => 'main_pages#home'
  match '/contact', :to => 'main_pages#contact'
  match '/login', :to => 'main_pages#login'
	controller :sessions do
	  get '/logout' => :destroy
	end

  match '/meetings_options', :to => 'main_pages#meetings_options'
  resources :meetings do
    post 'sign_to_meeting', :action => :sign_to_meeting
  end

end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  def home
  	#No hacemos nada, se muestra el home
 	end

 	def contact
  	#No hacemos nada, se muestra el contact
 	end

 	def login
  	#No hacemos nada, se muestra el login
 	end

 	def meetings_options
 		#No hacemos nada, se muestran las opciones de meetings
 	end
end

app/views/main_pages/contact.html.haml
= render :partial => 'menubars/menubar_contact'
%article.contact
	%h1#centered CONTACT
	%p#padding2
		Books on Rails is a web application where you can assist and create physical book enchanging meeting for librophiles all over the world. You can also manage your own collection of books while collaborating on the website catalog. 

	%p#padding2	
		This Web application is the result of an End of Degree Work (TFG). It was made by the Alfonso Peralta Calvo (student of Computer Engineering at University of Valladolid) and under the supervision of Yania Crespo González-Carvajal (Phd Professor of the University of Valladolid).

		%ul#details
			%li#padding2
				Developer's email:  
				=mail_to("fosiperalta@gmail.com")
			%li#padding2
				Developer's twitter:  
				=link_to "@fosiperalta", "http://twitter.com/fosiperalta"
			%li#padding2
				Developer's phone:  +34 660812332
			%br
			%li#padding2
				Supervisor's email:  
				=mail_to("yania@infor.uva.es")

app/views/main_pages/home.html.haml
//HOME
=render :partial => 'menubars/menubar_home'
%article.home
	%h1#centered HOME
	%p#padding2
		Welcome #{session[:current_user_username]}!
	%p#padding2
		Books on Rails is a web application where you can assist and create physical book enchanging meeting for librophiles all over the world. You can also manage your own collection of books while collaborating on the website catalog. 
		- @user = User.find(session[:current_user_id])
		%ul#details
			%li#padding2
				=link_to "MY BOOKS:", user_exemplars_path(@user)
				In this section you can manage your own collection of books. You can add books, delete them or view information about them!
			%br
			%li#padding2
				=link_to "MEETINGS:", meetings_options_path
				Here you can access to some options for managing the book-enchanging meetings.
			%br
			%li#padding2
				=link_to "CATALOG:", books_path(@user)
				You can also collaborate to enlarge the book catalog of the website. Every book counts!
			%br
			%li#padding2
				=link_to "ACCOUNT:", user_path(@user)
				You can administrate your account, view or edit account information on demand.
			%br

app/views/main_pages/meetings_options.html.haml
=render :partial => 'menubars/menubar_meetings'
%article.content
	%h1#centered MEETINGS OPTIONS
	#alinea10ypadding2#centered= link_to 'View all available meetings', meetings_path
	%div.tip#alinea10ypadding2#centered
		Select this if you want to see all the meetings created in the website
	- @user = User.find(session[:current_user_id])
	%br
	#alinea10ypadding2#centered= link_to 'View meetings I\'m assisting', user_assistances_path(@user)
	%div.tip#alinea10ypadding2#centered
		Select this if you want to see only the meetings you are assisting

	%br
	#alinea10ypadding2#centered= link_to 'Create new meeting', new_meeting_path
	%div.tip#alinea10ypadding2#centered
		With this option you can create new meetings
	%br