config/routes.rb
Booksonrails::Application.routes.draw do

  resources :books do
    post 'add_to_my_books', :action => :add_to_my_books
    post 'add_to_my_books2', :action => :add_to_my_books2
  end
  resources :users do
    resources :assistances do
      post 'take_book', :action => :take_book
      post 'untake_book', :action => :untake_book
    end
    resources :exemplars do
      get 'search_by_title', :on => :collection
    end
  end
  resources :sessions
  root :to => redirect('/sessions/new')
  match '/home', :to => 'main_pages#home'
  match '/contact', :to => 'main_pages#contact'
  match '/login', :to => 'main_pages#login'
	controller :sessions do
	  get '/logout' => :destroy
	end

  match '/meetings_options', :to => 'main_pages#meetings_options'
  resources :meetings do
    post 'sign_to_meeting', :action => :sign_to_meeting
  end

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	has_many :assistances
	#Evitamos el error al intentar hacer mass assignment
	attr_accessible :title
	attr_accessible :date
	attr_accessible :country
	attr_accessible :city
	attr_accessible :direction
	attr_accessible :creator


	#Validamos que existan una serie de atributos
	validates :title, :presence => true

	#Que sean unicos
	validates :title, uniqueness: true

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
    @meetings = Meeting.all
  end

	def show
	  id = params[:id] #Cogemos el id del meeting de la URI
	  @meeting = Meeting.find(id) 
	  #Por defecto va a mostrar app/views/meetings/show.html.haml
	end

	def new
		#genera la vista con el form para rellenar los datos
	end

	def create
			#coge los datos rellenados en el form de new y lanza el metodo
			#create! con esos parámetros
		@meeting = Meeting.new(params[:meeting])
		@meeting.creator = session[:current_user_username]
	  if @meeting.save
	  	flash[:notice] = "#{@meeting.title} was successfully created."
	    redirect_to meetings_path
	  else
	    render 'new'
	  end
	end

	def edit
		@meeting = Meeting.find params[:id]
	end

	def update
			#coge los datos del form de edit y lanza el metodo
			#update_atributes con esos parámetros
		 @meeting = Meeting.find params[:id]
	  if @meeting.update_attributes(params[:meeting])
	    flash[:notice] = "#{@meeting.title} was successfully updated."
	    redirect_to meeting_path(@meeting)
	  else
	    render 'edit'
	  end
	end

	def destroy
		#Eliminar un meeting
	  @meeting = Meeting.find(params[:id])
	  @meeting.destroy
	  flash[:notice] = " The meeting '#{@meeting.title}' was deleted."
	  redirect_to meetings_path
	end

		def sign_to_meeting
			#Creamos una asistencia con usuario+meeting
			flash[:notice] = "Assistance created"
			redirect_to meetings_path
	end

end

app/views/meetings/_meeting_form.html.haml
//Formulario comun a crear y editar libros

//De esta manera prevenimos que se creen libros en BD si existen errores 
//de validacion
- unless @meeting.nil? or @meeting.errors.empty?
  #warning
    Errors prevented this meeting from being #{controller.action_name}d:
    %ul
      - @meeting.errors.full_messages.each do |error|
        %li= error

#alinea10ypadding2= label :meeting, :title, 'Title'
#alinea10ypadding2= text_field :meeting, :title

#alinea10ypadding2= label :meeting, :date, 'Date'
#alinea10ypadding2= datetime_select( :meeting, :date, :order => [:day, :month, :year,:hour, :minute], prompt: { day: 'Day', month: 'Month', year: 'Year',hour: 'Hour', minute: 'Minute'}, start_year: 2015, end_year: 2017)

#alinea10ypadding2= label :meeting, :country, 'Country'
#alinea10ypadding2= text_field :meeting, :country

#alinea10ypadding2= label :meeting, :city, 'City'
#alinea10ypadding2= text_field :meeting, :city

#alinea10ypadding2= label :meeting, :direction, 'Address'
#alinea10ypadding2= text_field :meeting, :direction

app/views/meetings/edit.html.haml
=render :partial => 'menubars/menubar_meetings'
%article.content
	%h1#centered MEETINGS
	%h2#alinea10ypadding2 Edit Meeting

	=form_tag meeting_path(@meeting), :method => :put do
		#alinea10ypadding2= render :partial => 'meeting_form'
		%br
		#alinea10ypadding2= submit_tag 'Save Changes'

app/views/meetings/index.html.haml
//Mostrar todos los libros disponibles en BD
=render :partial => 'menubars/menubar_meetings'
%article.content
  %h1#centered MEETINGS
  %p#alinea10ypadding2
    Here you can assist to one of the created meetings, edit your assistance if it exists and view the info of a given meeting. The meetings you are going to assist are shown in blue, the rest in yellow.
  %table#books
    %thead
      %tr
        %th Title
        %th Date
        %th Country
        %th City
        %th Assistance
        %th Delete
    %tbody
      -# this goes just inside %body:
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
      - @user = User.find(session[:current_user_id])
      - @meetings.each do |meeting|
        - @assistance = Assistance.where(user_id: @user.id.to_s, meeting_id: meeting.id.to_s).last
        -if meeting.creator == session[:current_user_username]
          -if @assistance.nil?
            %tr#nottaken
              %td= link_to meeting.title + " (Created by me)", meeting_path(meeting)
              %td= meeting.date
              %td= meeting.country
              %td= meeting.city
              -if @assistance.nil?
                %td= link_to "Assist to meeting", user_assistance_path(@user, meeting)
              -else
                %td= link_to "Edit assistance", user_assistance_path(@user, meeting)
              %td= button_to 'Delete',  meeting_path(meeting), :method => :delete, :confirm => 'Are you sure?'
          -else
            %tr#taken
              %td= link_to meeting.title + " (Created by me)", meeting_path(meeting)
              %td= meeting.date
              %td= meeting.country
              %td= meeting.city
              -if @assistance.nil?
                %td= link_to "Assist to meeting", user_assistance_path(@user, meeting)
              -else
                %td= link_to "Edit assistance", user_assistance_path(@user, meeting)
              %td= button_to 'Delete',  meeting_path(meeting), :method => :delete, :confirm => 'Are you sure?'
        -else
          -if @assistance.nil?
            %tr#nottaken
              %td= link_to meeting.title, meeting_path(meeting) 
              %td= meeting.date
              %td= meeting.country
              %td= meeting.city
              -if @assistance.nil?
                %td= link_to "Assist to meeting", user_assistance_path(@user, meeting)
              -else
                %td= link_to "Edit assistance", user_assistance_path(@user, meeting)
              %td Unavailable
          -else
            %tr#taken
              %td= link_to meeting.title, meeting_path(meeting) 
              %td= meeting.date
              %td= meeting.country
              %td= meeting.city
              -if @assistance.nil?
                %td= link_to "Assist to meeting", user_assistance_path(@user, meeting)
              -else
                %td= link_to "Edit assistance", user_assistance_path(@user, meeting)
              %td Unavailable
  %br
  #alinea10ypadding2= link_to 'Create new meeting', new_meeting_path
  %br

app/views/meetings/new.html.haml
=render :partial => 'menubars/menubar_meetings'
%article.content
	%h2#centered Create New Meeting
	
	= form_tag meetings_path, :method => :post do
		= render :partial => 'meeting_form'
		%br
		#alinea10ypadding2= submit_tag 'Save Changes'

app/views/meetings/show.html.haml
=render :partial => 'menubars/menubar_meetings'
%article.content
  %h1#centered MEETING
  %h2#alinea10ypadding2 Details about #{@meeting.title}

  %ul#details
    %li#alinea10ypadding2
      Title
      =@meeting.title
    %li#alinea10ypadding2
      Date:
      = @meeting.date
    %li#alinea10ypadding2
      Country:
      = @meeting.country
    %li#alinea10ypadding2
      City:
      = @meeting.city
    %li#alinea10ypadding2
      Address:
      = @meeting.direction
    %li#alinea10ypadding2
      Creator:
      = @meeting.creator

  -@assistances = Assistance.where(meeting_id: @meeting.id.to_s)

  %table#books
    %thead
      %tr
        %th User
        %th Books
    %tbody
      -# this goes just inside %body:
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
        
      - @assistances.each do |assistance|
        -user = User.find(assistance.user_id)
        %tr
          %td= user.username
          -linea=""
          -unless assistance.books.nil?
            -assistance.books.each do |book|
              -linea = Book.find(book).title + ", " + linea
          %td= linea

  -if @meeting.creator == session[:current_user_username]
    %br
    #alinea10ypadding2= link_to 'Edit info', edit_meeting_path(@meeting)
    #alinea10ypadding2= button_to 'Delete', meeting_path(@meeting), :method => :delete, :confirm => 'Are you sure?'
  %br
  #alinea10ypadding2= link_to 'Back to meetings list', meetings_path