config/routes.rb
Booksonrails::Application.routes.draw do

  resources :books do
    post 'add_to_my_books', :action => :add_to_my_books
    post 'add_to_my_books2', :action => :add_to_my_books2
  end
  resources :users do
    resources :assistances do
      post 'take_book', :action => :take_book
      post 'untake_book', :action => :untake_book
    end
    resources :exemplars do
      get 'search_by_title', :on => :collection
    end
  end
  resources :sessions
  root :to => redirect('/sessions/new')
  match '/home', :to => 'main_pages#home'
  match '/contact', :to => 'main_pages#contact'
  match '/login', :to => 'main_pages#login'
	controller :sessions do
	  get '/logout' => :destroy
	end

  match '/meetings_options', :to => 'main_pages#meetings_options'
  resources :meetings do
    post 'sign_to_meeting', :action => :sign_to_meeting
  end

end

app/models/assistance.rb
class Assistance < ActiveRecord::Base
  belongs_to :user
  belongs_to :meeting

  validates :user_id, :presence => true
  validates :meeting_id, :presence => true

  validates_uniqueness_of :user_id, scope: :meeting_id

  attr_accessible :user_id
  attr_accessible :meeting_id
  attr_accessible :books

  serialize :books
end

app/controllers/assistances_controller.rb
class AssistancesController < ApplicationController
  before_filter :has_user_and_meeting, :only => [:new, :create]
  protected
  def has_user_and_meeting
  end

  public
  
  def new
  end

  def create
  end

  def show
    @user = User.find(params[:user_id])
    @meeting = Meeting.find(params[:id])
    exemplars = User.find(session[:current_user_id]).exemplars.all
    @books ||= Array.new
    exemplars.each do |e|
    #Book.all.each do |e|
      if(!e.book.nil?)
        @books.push(e.book)
      end
    end
  end

  def index
    assistances = User.find(session[:current_user_id]).assistances.all
    @meetings ||= Array.new
    assistances.each do |a|
    	@meetings.push(a.meeting)
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @meeting = Meeting.find(params[:id])
    @assistance = Assistance.where(user_id: @user.id.to_s, meeting_id: @meeting.id.to_s)
    @assistance.destroy_all
    flash[:warning] = "Assistance to '#{@meeting.title}' removed"
    redirect_to user_assistances_path(@user)
  end

  def take_book
    @user = User.find(params[:user_id])
    @meeting = Meeting.find(params[:assistance_id])
    @book = Book.find(params[:format])
    @assistance = Assistance.where(user_id: @user.id.to_s, meeting_id: @meeting.id.to_s).last
    if @assistance.nil?
      @assistance = Assistance.new(user_id: @user.id.to_s, meeting_id: @meeting.id.to_s, books: [])
      @assistance.save
      flash[:notice] = "Assistance created"
    end
    @assistance.books.push(@book.id)
    @assistance.save
    flash[:notice] = "book taken"
    redirect_to user_assistance_path(@user, @meeting)
  end

  def untake_book
    @user = User.find(params[:user_id])
    @meeting = Meeting.find(params[:assistance_id])
    @book = Book.find(params[:format])
    @assistance = Assistance.where(user_id: @user.id.to_s, meeting_id: @meeting.id.to_s).last
    @assistance.books.delete(@book.id)
    @assistance.save
    flash[:notice] = "book Removed"
    redirect_to user_assistance_path(@user, @meeting)
  end
end

app/views/assistances/index.html.haml
//Mostrar todos los libros disponibles en BD
=render :partial => 'menubars/menubar_meetings'
%article.content
  %h1#centered ASSISTANCES

  %table#books
    %thead
      %tr
        %th Title
        %th Date
        %th Country
        %th City
        %th Assistance
        %th Books
    %tbody
      -# this goes just inside %body:
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
      -@user = User.find(params[:user_id])
      -@meetings.each do |meeting|
        %tr
          %td= link_to meeting.title, meeting_path(meeting)
          %td= meeting.date
          %td= meeting.country
          %td= meeting.city
          %td= button_to 'Remove assistance',  user_assistance_path(@user,meeting), :method => :delete, :confirm => 'Are you sure?'
          -@assistance = Assistance.where(user_id: @user.id.to_s, meeting_id: meeting.id.to_s).last
          -linea = ""
          -unless @assistance.books.nil?
            -@assistance.books.each do |book|
              -linea = Book.find(book).title + ", " + linea
          %td= linea
  %br

app/views/assistances/show.html.haml
//Mostrar todos los libros disponibles en BD
=render :partial => 'menubars/menubar_meetings'
%article.content
  %h1#centered ASSISTANCE TO #{@meeting.title.upcase}

  %ul#details
    %li#alinea10ypadding2
      Title:
      =@meeting.title
    %li#alinea10ypadding2
      Date:
      = @meeting.date
    %li#alinea10ypadding2
      Country:
      = @meeting.country
    %li#alinea10ypadding2
      City:
      = @meeting.city
    %li#alinea10ypadding2
      Address:
      = @meeting.direction
    %li#alinea10ypadding2
      Creator:
      = @meeting.creator
    %li#alinea10ypadding2
      Books I'm taking:
      - books_line=""
      -@assistance = Assistance.where(user_id: @user.id.to_s, meeting_id: @meeting.id.to_s).last
      -unless @assistance.nil?
        -@assistance.books.each do |b|
          -book = Book.find(b)
          =book.title + ","
              
  %table#books
    %thead
      %tr
        %th Book
        %th Take to meeting
    %tbody
      -# this goes just inside %body:
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
        
      - @books.each do |book|
        - @assistance = Assistance.where(user_id: @user.id.to_s, meeting_id: @meeting.id.to_s).last
        -if @assistance.nil?
          %tr#nottaken
            %td= book.title
            %td= button_to 'Take book to meeting', user_assistance_take_book_path(@user, @meeting, book)
        -elsif @assistance.books.include?(book.id)
          %tr#taken
            %td= book.title
            %td= button_to 'Remove book from meeting', user_assistance_untake_book_path(@user, @meeting, book)
        -else
          %tr#nottaken
            %td= book.title
            %td= button_to 'Take book to meeting', user_assistance_take_book_path(@user, @meeting, book)
  %br