config/routes.rb
Booksonrails::Application.routes.draw do

  resources :books do
    post 'add_to_my_books', :action => :add_to_my_books
    post 'add_to_my_books2', :action => :add_to_my_books2
  end
  resources :users do
    resources :assistances do
      post 'take_book', :action => :take_book
      post 'untake_book', :action => :untake_book
    end
    resources :exemplars do
      get 'search_by_title', :on => :collection
    end
  end
  resources :sessions
  root :to => redirect('/sessions/new')
  match '/home', :to => 'main_pages#home'
  match '/contact', :to => 'main_pages#contact'
  match '/login', :to => 'main_pages#login'
	controller :sessions do
	  get '/logout' => :destroy
	end

  match '/meetings_options', :to => 'main_pages#meetings_options'
  resources :meetings do
    post 'sign_to_meeting', :action => :sign_to_meeting
  end

end

app/models/exemplar.rb
class Exemplar < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  validates :user_id, :presence => true
  validates :book_id, :presence => true

  attr_accessible :user_id
  attr_accessible :book_id
  attr_accessible :shareable
end

app/controllers/exemplars_controller.rb
class ExemplarsController < ApplicationController
  before_filter :has_user_and_book, :only => [:new, :create]
  protected
  def has_user_and_book
  end

  public
  
  def new
  end

  def create
  end

  def index
    exemplars = User.find(session[:current_user_id]).exemplars.all
    @books ||= Array.new
    exemplars.each do |e|
    	@books.push(e.book)
    end
  end

  def destroy
    #Eliminar un ejemplar de my books
    @user = User.find(params[:user_id])
    @book = Book.find(params[:id])
    @exemplar = Exemplar.where(user_id: @user.id.to_s, book_id: @book.id.to_s)
    @exemplar.destroy_all
    flash[:notice] = "An exemplar of '#{@book.title}' deleted from My Books."
    redirect_to user_exemplars_path(@user)
  end

  def search_by_title
    exemplars = User.find(session[:current_user_id]).exemplars.all
    @books ||= Array.new
    exemplars.each do |e|
      @books.push(e.book)
    end

    @user = User.find(params[:user_id])
    @title = params[:title]
    allBooks = Book.all
    @searchedBooks ||= Array.new
    allBooks.each do |b|
      if (!b.title.nil? and !@title.nil?)
        if (b.title.downcase.include?(@title))
          @exemplar = Exemplar.where(user_id: @user.id.to_s, book_id: b.id.to_s)
          if(@exemplar == [])
            @searchedBooks.push(b)
          end
        end
      end
    end
    render 'index'
  end
end

app/views/exemplars/index.html.haml
//Mostrar todos los libros disponibles en BD
=render :partial => 'menubars/menubar_mybooks'
%article.content
  %h1#centered MY BOOKS
  %p#alinea10
    Here you can manage all the books in your collection. 
  %table#books
    %thead
      %tr
        %th Title
        %th Author
        %th Publisher
        %th Language
        %th Remove from My Books
    %tbody
      -# this goes just inside %body:
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
        
      - @books.each do |book|
        -if (!book.nil?)  
          %tr
            %td= link_to book.title, book_path(book) 
            %td= book.author
            %td= book.publisher
            %td= book.language
            - @user = User.find(session[:current_user_id])
            %td= button_to 'Remove',  user_exemplar_path(@user,book), :method => :delete, :confirm => 'Are you sure?'
  %br
  %div#alinea10
    Do you want to add some more books?
  = form_tag({:controller => "exemplars", :action => "search_by_title"}, {:method => "get"}) do
    #alinea10ypadding2= label :title, 'Search by title'
    #alinea10ypadding2= text_field_tag "title"
    #alinea10ypadding2= submit_tag "Search"

  %br
  %h2#alinea10 
    Search results 
    =image_tag "search.png"
  %p#alinea10 
    Books whose title includes "#{@title}"...
  -if(!@searchedBooks.nil?)
    %table#books
      %thead
        %tr
          %th Title
          %th Author
          %th Publisher
          %th Language
          %th Remove from My Books
      %tbody
        -# this goes just inside %body:
        - if flash[:notice]
          #notice.message= flash[:notice]
        - elsif flash[:warning]
          #warning.message= flash[:warning]
          
        - @searchedBooks.each do |book|
          %tr
            %td= link_to book.title, book_path(book) 
            %td= book.author
            %td= book.publisher
            %td= book.language
            - @user = User.find(session[:current_user_id])
            %td= button_to "Add to My Books", book_add_to_my_books2_path(book)

          

app/views/exemplars/search_by_title.html.haml
//Mostrar todos los libros disponibles en BD
=render :partial => 'menubars/menubar_mybooks'
%h1 MY BOOKS

%table#books
  %thead
    %tr
      %th Title
      %th Author
      %th Publisher
      %th Language
      %th Add to My Books
  %tbody
    -# this goes just inside %body:
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
      
    - @books.each do |book|
      %tr
        %td= link_to book.title, book_path(book) 
        %td= book.author
        %td= book.publisher
        %td= book.language
        - @user = User.find(session[:current_user_id])
        %td EEE
        

= label :book, :title, 'Search by title'
= text_field :book, :title
=button_to "Search", search_by_title_user_exemplars_path(), method: :get

- form_tag(:action => :search_by_title) do
  / basic_hydraulics = method in controller
  = label :book, :title, 'Search by title'
  = text_field :book, :title
  = submit_tag "Search"